require("alexandre.packer")
require("alexandre.keymap")
require("alexandre.options")
require("alexandre.treesitter")
require("alexandre.cmp")
require("alexandre.lspconfig")
require("alexandre.command")
require("alexandre.mason")
require("alexandre.themes")
require("alexandre.luacheck")
require("alexandre.lualine")
require("alexandre.noice")
require("alexandre.trouble")
require("alexandre.go")

