require("alexandre.packer")
require("alexandre.keymap")
require("alexandre.options")
require("alexandre.treesitter")
require("alexandre.cmp")
require("alexandre.lspconfig")
require("alexandre.neodev")
